# SearxNG configuration for DxG Benchmark App
use_default_settings: true

general:
  debug: false
  instance_name: "DxG Search"

search:
  safe_search: 0
  default_lang: "en"
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "461810547b73a15acf79e7883fc038af829d4bec138f3d5299aa33f13a9fc471"
  limiter: false
  image_proxy: true
  public_instance: false

ui:
  static_use_hash: true
  default_locale: "en"
  default_theme: simple

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: wikipedia
    engine: wikipedia
    shortcut: wp

enabled_plugins:
  - 'Hash plugin'
  - 'Tracker URL remover'

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  enable_http2: false

redis:
  url: redis://172.20.0.11:6379/0

botdetection:
  ip_lists:
    pass_ip: 
      - '172.20.0.0/16'
  http_accept: false
  http_accept_encoding: false
  http_accept_language: false
  http_user_agent: false
